version: "3.3"

services:
  postgres:
    container_name: url-pg-db
    image: bitnami/postgresql:latest
    ports:
      - "5482:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/bitnami/postgresql

  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Painel do Traefik (opcional)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
volumes:
  postgres_data:  