version: "3.3"

services:
  postgres:
    container_name: url-pg-db
    image: bitnami/postgresql:latest
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/pg
    volumes:
      - ./data/pg:/data/pg
