# Mimir minimal config for single node
multitenancy_enabled: false

blocks_storage:
  backend: filesystem
  filesystem:
    dir: /tmp/mimir/data/blocks

server:
  http_listen_port: 9009
  grpc_listen_port: 9008
